name: Deploy to GitHub pages
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Generate static files
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - run: npm ci
              working-directory: ./frontend

            - run: npm run build
              working-directory: ./frontend
              env:
                  VUE_APP_DEMO: true

            - name: Init new repo in dist folder and commit generated files
              run: |
                  cd dist
                  git init
                  git add -A
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m 'deploy'
              working-directory: ./frontend
            - name: Force push to destination branch
              uses: ad-m/github-push-action@v0.5.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  force: true
                  directory: ./frontend/dist
